### PR TITLE
Nv orders Tickets #2, #6, #16, #9 + extras

### PR DESCRIPTION
**Pull request by navogel**
Created shopping cart page:

shopping cart shows the current uncompleted order with lists of all items.  If no uncompleted order exists, redirected to completed orders page with warning message.  If shopping cart exists, user can review items (listed by line and grouped by product type - so if there are 2 or more of one product they show on the same line with total cost).  User can click on add payment, and go to a payment screen.  Upon completion they are redirected back to completed orders page with success message.

### CODE REVIEW

**Comment by navogel** [comment]
Ok, went ahead and added ticket 6 to this.  now user can delete single items from the shopping cart, cart updates, and now there is a total price at the bottom that also updates.

**Comment by navogel** [comment]
realized that ticket 16 was also completed, just needed to add a link to the account page.  Ticket 16 complete!

**Comment by navogel** [comment]
and went ahead and added a delete order function to the orders controller.

**Comment by FortunatoMugnano** [comment]
Very good job, it works very well

**Pull request merged**
